// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoK2DpmgdfKV2VMHgDPTTm8zUsZvPBG5A',
    appId: '1:1091272786074:web:1240f85f3ba22eeea59f23',
    messagingSenderId: '1091272786074',
    projectId: 'apprenticeship-mobile',
    authDomain: 'apprenticeship-mobile.firebaseapp.com',
    storageBucket: 'apprenticeship-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9zZkrd-lGulluMTbYuwFh4FAYLBShzXI',
    appId: '1:1091272786074:android:bd4fe7fa512257e4a59f23',
    messagingSenderId: '1091272786074',
    projectId: 'apprenticeship-mobile',
    storageBucket: 'apprenticeship-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw6chjW-zd5NYiVpIjbpVvhU3B6fkKlro',
    appId: '1:1091272786074:ios:39a809a4a2d67b54a59f23',
    messagingSenderId: '1091272786074',
    projectId: 'apprenticeship-mobile',
    storageBucket: 'apprenticeship-mobile.appspot.com',
    iosBundleId: 'com.example.funBloc',
  );
}
